# Generated by Django 4.0.6 on 2022-10-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='civil1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='civil2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='civil3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='civil4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='cse1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='cse2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='cse3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='cse4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='ece1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='ece2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='ece3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='ece4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='eee1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='eee2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='eee3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='eee4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='it1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='it2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='it3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='it4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='mech1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='mech2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='mech3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='mech4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
            ],
        ),
    ]
