# Generated by Django 4.0.6 on 2022-11-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_college_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffName', models.TextField(max_length=50)),
                ('staffDep', models.TextField(max_length=40)),
                ('staffCollege', models.TextField()),
                ('staffPosition', models.TextField(max_length=20)),
                ('staffUsername', models.TextField(max_length=20)),
                ('staffPassword', models.TextField(max_length=20)),
            ],
        ),
    ]
