# Generated by Django 4.0.6 on 2022-11-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('s_mobile', models.IntegerField(verbose_name=20)),
                ('p_mobile', models.IntegerField(verbose_name=20)),
                ('attendance', models.BooleanField(default=False)),
                ('clg', models.TextField()),
                ('department', models.TextField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
