# Generated by Django 4.0.6 on 2022-11-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.TextField(),
        ),
    ]
