# Generated by Django 4.0.6 on 2022-11-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_student_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='civil1',
        ),
        migrations.DeleteModel(
            name='civil2',
        ),
        migrations.DeleteModel(
            name='civil3',
        ),
        migrations.DeleteModel(
            name='civil4',
        ),
        migrations.DeleteModel(
            name='cse1',
        ),
        migrations.DeleteModel(
            name='cse2',
        ),
        migrations.DeleteModel(
            name='cse3',
        ),
        migrations.DeleteModel(
            name='cse4',
        ),
        migrations.DeleteModel(
            name='ece1',
        ),
        migrations.DeleteModel(
            name='ece2',
        ),
        migrations.DeleteModel(
            name='ece3',
        ),
        migrations.DeleteModel(
            name='ece4',
        ),
        migrations.DeleteModel(
            name='eee1',
        ),
        migrations.DeleteModel(
            name='eee2',
        ),
        migrations.DeleteModel(
            name='eee3',
        ),
        migrations.DeleteModel(
            name='eee4',
        ),
        migrations.DeleteModel(
            name='it1',
        ),
        migrations.DeleteModel(
            name='it2',
        ),
        migrations.DeleteModel(
            name='it3',
        ),
        migrations.DeleteModel(
            name='it4',
        ),
        migrations.DeleteModel(
            name='mech1',
        ),
        migrations.DeleteModel(
            name='mech2',
        ),
        migrations.DeleteModel(
            name='mech3',
        ),
        migrations.DeleteModel(
            name='mech4',
        ),
    ]
