# Generated by Django 4.0.6 on 2022-11-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_delete_civil1_delete_civil2_delete_civil3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='college',
            name='username',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffDep',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffName',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffPassword',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffPosition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffUsername',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='p_mobile',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_mobile',
            field=models.TextField(),
        ),
    ]
